# Generated by Django 3.2.6 on 2021-09-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Fanning nomi')),
            ],
            options={
                'verbose_name': 'Fan nomi',
                'verbose_name_plural': 'Fan nomlari',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('lesson_date', models.DateField(verbose_name='Mavzu sanasi')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='all_docs/', verbose_name="Faqat 'doc' va 'docx' xujjatlarni yuklang!")),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text uchun')),
                ('powerpoint_file', models.FileField(blank=True, null=True, upload_to='all_powerpoint/', verbose_name='Slay uchun')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='all_video/', verbose_name='Video fayl uchun')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='all_audio/', verbose_name='Audio fayl uchun')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='all_photo/', verbose_name='Foto fayl uchun')),
                ('responsible_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Bo'lim/Gurux")),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subjects', verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Mavzusi',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='UserThemeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='all_user_records/', verbose_name='Foydalanuvchi audio yozuvlari')),
                ('date_educated', models.DateTimeField(auto_now_add=True, verbose_name="Mavzu o'rganilgan sana")),
                ('test_results', models.IntegerField(verbose_name='Test natijasi')),
                ('edited_theme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.themes', verbose_name='Tanlangan mavzu nomi')),
                ('user_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Mavzuni o'tgan",
                'verbose_name_plural': "Mavzuni o'tgan",
                'db_table': 'editers_theme',
            },
        ),
        migrations.CreateModel(
            name='Sections_and_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_group', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name="Bo'lim yoki gurux nomi")),
            ],
            options={
                'verbose_name': "Bo'lim va gurux",
                'verbose_name_plural': "Bo'lim va guruxlar",
                'db_table': 'sectionsandgroups',
            },
        ),
    ]
