# Generated by Django 3.2.6 on 2021-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='powerpoint_file',
            field=models.FileField(blank=True, null=True, upload_to='all_powerpoint/', verbose_name='Slay uchun'),
        ),
    ]
